name: Tests HM

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

concurrency:
    group: ${{ github.head_ref }}-required-tests
    cancel-in-progress: true

env:
    python-version: 3.9.7

jobs:
    pre_job:
      # continue-on-error: true # Uncomment once integration is finished
        runs-on: ubuntu-latest
      # Map a step output to a job output
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@master
              with:
                  paths_ignore: '["infra/**", "doc/**", ".github/**"]'

    tests:
        timeout-minutes: 30
        name: Tests HM
        runs-on: ubuntu-latest
        needs: pre_job
        if: ${{ github.event.pull_request.draft == false }} and ${{ needs.pre_job.outputs.should_skip != 'true'
            }}
        steps:
            - name: Check the code out
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GITBOT_TOKEN }}
                  submodules: true

            - name: step
              run: echo "Hello world!"
